version: '3.8'

services:
  # Servicio 1: La API de Python (OCR)
  python_ocr_api:
    build: ./python-api
    container_name: python_ocr_api
    restart: always
    # No necesita puertos hacia afuera porque n8n le habla por la red interna

  # Servicio 2: n8n
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_ocr
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - WEBHOOK_URL=${WEBHOOK_URL} # Lee la URL completa del .env
      - N8N_PORT=5678
    volumes:
      - ./n8n_data:/home/node/.local/share/n8n

  # Servicio 3: Ngrok (El túnel)
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: always
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "n8n:5678"
      - "--domain=${NGROK_DOMAIN}" # Usa tu dominio fijo de Ngrok
    depends_on:
      - n8n

volumes:
  n8n_data: